# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Chord.create!([
  { name: "A", image: "A.png", root: "A", alteration: "none", quality: "major", option: "none" },
  { name: "Am", image: "Am.png", root: "A", alteration: "none", quality: "minor", option: "none" },
  { name: "A7", image: "A7.png", root: "A", alteration: "none", quality: "major", option: "7" },
  { name: "Am7", image: "Am7.png", root: "A", alteration: "none", quality: "minor", option: "7" },
  { name: "Amaj7", image: "Amaj7.png", root: "A", alteration: "none", quality: "major", option: "maj7" },
  { name: "A6", image: "A6.png", root: "A", alteration: "none", quality: "major", option: "6" },
  { name: "Adim", image: "Adim.png", root: "A", alteration: "none", quality: "dim", option: "none" },
  { name: "B", image: "B.png", root: "B", alteration: "none", quality: "major", option: "none" },
  { name: "Bm", image: "Bm.png", root: "B", alteration: "none", quality: "minor", option: "none" },
  { name: "B7", image: "B7.png", root: "B", alteration: "none", quality: "major", option: "7" },
  { name: "Bm7", image: "Bm7.png", root: "B", alteration: "none", quality: "minor", option: "7" },
  { name: "Bmaj7", image: "Bmaj7.png", root: "B", alteration: "none", quality: "major", option: "maj7" },
  { name: "B6", image: "B6.png", root: "B", alteration: "none", quality: "major", option: "6" },
  { name: "Bdim", image: "Bdim.png", root: "B", alteration: "none", quality: "dim", option: "none" },
  { name: "C", image: "C.png", root: "C", alteration: "none", quality: "major", option: "none" },
  { name: "Cm", image: "Cm.png", root: "C", alteration: "none", quality: "minor", option: "none" },
  { name: "C7", image: "C7.png", root: "C", alteration: "none", quality: "major", option: "7" },
  { name: "Cm7", image: "Cm7.png", root: "C", alteration: "none", quality: "minor", option: "7" },
  { name: "Cmaj7", image: "Cmaj7.png", root: "C", alteration: "none", quality: "major", option: "maj7" },
  { name: "C6", image: "C6.png", root: "C", alteration: "none", quality: "major", option: "6" },
  { name: "Cdim", image: "Cdim.png", root: "C", alteration: "none", quality: "dim", option: "none" },
  { name: "D", image: "D.png", root: "D", alteration: "none", quality: "major", option: "none" },
  { name: "Dm", image: "Dm.png", root: "D", alteration: "none", quality: "minor", option: "none" },
  { name: "D7", image: "D7.png", root: "D", alteration: "none", quality: "major", option: "7" },
  { name: "Dm7", image: "Dm7.png", root: "D", alteration: "none", quality: "minor", option: "7" },
  { name: "Dmaj7", image: "Dmaj7.png", root: "D", alteration: "none", quality: "major", option: "maj7" },
  { name: "D6", image: "D6.png", root: "D", alteration: "none", quality: "major", option: "6" },
  { name: "Ddim", image: "Ddim.png", root: "D", alteration: "none", quality: "dim", option: "none" },
  { name: "E", image: "E.png", root: "E", alteration: "none", quality: "major", option: "none" },
  { name: "Em", image: "Em.png", root: "E", alteration: "none", quality: "minor", option: "none" },
  { name: "E7", image: "E7.png", root: "E", alteration: "none", quality: "major", option: "7" },
  { name: "Em7", image: "Em7.png", root: "E", alteration: "none", quality: "minor", option: "7" },
  { name: "Emaj7", image: "Emaj7.png", root: "E", alteration: "none", quality: "major", option: "maj7" },
  { name: "E6", image: "E6.png", root: "E", alteration: "none", quality: "major", option: "6" },
  { name: "Edim", image: "Edim.png", root: "E", alteration: "none", quality: "dim", option: "none" },
  { name: "F", image: "F.png", root: "F", alteration: "none", quality: "major", option: "none" },
  { name: "Fm", image: "Fm.png", root: "F", alteration: "none", quality: "minor", option: "none" },
  { name: "F7", image: "F7.png", root: "F", alteration: "none", quality: "major", option: "7" },
  { name: "Fm7", image: "Fm7.png", root: "F", alteration: "none", quality: "minor", option: "7" },
  { name: "Fmaj7", image: "Fmaj7.png", root: "F", alteration: "none", quality: "major", option: "maj7" },
  { name: "F6", image: "F6.png", root: "F", alteration: "none", quality: "major", option: "6" },
  { name: "Fdim", image: "Fdim.png", root: "F", alteration: "none", quality: "dim", option: "none" },
  { name: "G", image: "G.png", root: "G", alteration: "none", quality: "major", option: "none" },
  { name: "Gm", image: "Gm.png", root: "G", alteration: "none", quality: "minor", option: "none" },
  { name: "G7", image: "G7.png", root: "G", alteration: "none", quality: "major", option: "7" },
  { name: "Gm7", image: "Gm7.png", root: "G", alteration: "none", quality: "minor", option: "7" },
  { name: "Gmaj7", image: "Gmaj7.png", root: "G", alteration: "none", quality: "major", option: "maj7" },
  { name: "G6", image: "G6.png", root: "G", alteration: "none", quality: "major", option: "6" },
  { name: "Gdim", image: "Gdim.png", root: "G", alteration: "none", quality: "dim", option: "none" },
])
